### ISSUE TITLE
Icon button broken in a Treetable header

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#818]
When using an icon button in a `clr-treetable` the button is not shown correctly.

![image](https://user-images.githubusercontent.com/123199/86351686-f61bf400-bc64-11ea-8bc9-587cb7453964.png)

**Comment by derkoe** [comment]
Reason for this seems to be this CSS rule

```css
treetable-host .treetable .treetable-row-scrollable :first-child {
    padding-left: 1.5rem;
}
```

**Comment by derkoe** [comment]
A workaround is to add this to your stylesheet

```css
.treetable-host .treetable .treetable-row-scrollable :first-child {
  padding-left: revert;
}
```
