### ISSUE TITLE
Treetable header expand button drops through

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/clarity-addons#838]
![image](https://user-images.githubusercontent.com/123199/88389652-29aaf380-cdb7-11ea-933d-ecaa4006d5ef.png)

**Comment by derkoe** [comment]
The reason for this is the z-index of header is lower than the expandable caret.

Workaround:
```scss
.treetable-host .treetable .treetable-header {
  z-index: 592; // workaround for z-index in .treetable-host .treetable .treetable-expandable-caret
}
```
