### ISSUE TITLE
Conflict with Clarity v4.0.8 DatePicker

### ISSUE THREAD

**Issue by jerone** [porscheinformatik/clarity-addons#962]
## Describe the bug

Clarity v4.0.8 introduced some CSS that conflicts with Clarity Addons for the DatePicker.

The DatePicker has no width anymore (see screenshot in reproduce section).

## To Reproduce

1. Install Clarity v4.0.8.
2. Add DatePicker.
3. See DatePicker having no width anymore: 
   ![image](https://user-images.githubusercontent.com/55841/103640203-df29c780-4f4f-11eb-8c52-798d410c8907.png)

## Expected behavior

I expect the DatePicker to have it's normal width again.

![image](https://user-images.githubusercontent.com/55841/103640527-71ca6680-4f50-11eb-948f-9cf6c316048b.png)

## Versions

**App**

- Angular: 10
- Node: v14.15.3
- Clarity: v4.0.8
- Clarity-Addons: v9.1.2

**Device:**

- Multiple browsers.

## Additional context

It appears to be introduced in this PR: https://github.com/vmware/clarity/pull/5238

Disabling the following code, fixed the issue:
![image](https://user-images.githubusercontent.com/55841/103640491-637c4a80-4f50-11eb-8b9e-c29b03ef4dd9.png)

**Comment by Wallabeng** [comment]
Hy @jerone,

Clarity Addons and Clarity have tightly coupled versions. That's why we added the exact version as peer dependencies.
Reason for this is (as you saw), that we override some CSS and recompile the whole SCSS into our own CSS themes.

So to fix this, an upgrade of clarity to 4.0.8 is needed and adaptions in CSS have to be done (if needed, after upgrading).

If you need this urgently feel free to contribute, as currently I don't have resources to do so.

**Comment by jerone** [comment]
I understand what you are saying about tightly coupled with Clarity. And if I find a solution, I'll try to contribute it.

However, if my assumption is correct, and the reason why this happening is because of the linked PR above, then this issue happens with Clarity v4.0.6 too (which is the official coupled version, according to the `package.json`).

I have yet to confirm this situation.

**Comment by jerone** [comment]
Link to Clarity v4.0.6 release notes, containing link to above mentioned PR: https://clarity.design/news/4.0.6

**Comment by jerone** [comment]
Work-around for in your project CSS file:

```css
// Fix bug with width of DatePickers was incorrectly overridden in Clarity Addons.
// See https://github.com/porscheinformatik/clarity-addons/issues/962
.clr-date-container .clr-input-group > .clr-input:not([clrdatalistinput]) {
	width: auto;
}
```
